In [49]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

from sklearn.model_selection import train_test_split, StratifiedKFold, cross_validate, StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, precision_score
from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score 
from sklearn.metrics import f1_score, roc_auc_score
from scipy.stats import skew
from scipy.stats import kurtosis

## Dataset loading - ucitavanje dataseta

In [50]:
df=pd.read_excel('../datasets/dataset2.xlsx')

## Display info about data and first five columns - prikaz informacija o datasetu i prvih 5 kolona iz dataseta

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 998 entries, 0 to 997
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ime                      998 non-null    object
 1   dob                      998 non-null    int64
 2   trudnoca_po_redu         998 non-null    object
 3   tetanus_vakcina_po_redu  998 non-null    object
 4   sedmica_trudnoce         998 non-null    object
 5   tezina                   998 non-null    object
 6   visina                   998 non-null    object
 7   krvni_pritisak           998 non-null    object
 8   anemija                  123 non-null    object
 9   zutica                   12 non-null     object
 10  polozaj_fetusa           998 non-null    object
 11  pokreti_fetusa           998 non-null    object
 12  otkucaji_srca_fetusa     998 non-null    object
 13  albumin_urin             134 non-null    object
 14  test_urina_za_dijabetes  998 non-null    object
 15  sifillis                 998 non-null    object
 16  hepatitisb               998 non-null    object
 17  rizicna_trudnoca         998 non-null    object
dtypes: int64(1), object(17)
memory usage: 140.5+ KB

In [52]:
df.head()

,ime,dob,trudnoca_po_redu,tetanus_vakcina_po_redu,sedmica_trudnoce,tezina,visina,krvni_pritisak,anemija,zutica,polozaj_fetusa,pokreti_fetusa,otkucaji_srca_fetusa,albumin_urin,test_urina_za_dijabetes,sifillis,hepatitisb,rizicna_trudnoca
0,Rituporna,18,1st,1st,38 week,50 kg,5.3'',100/60,NaN,NaN,Normal,Normal,140m,NaN,Yes,Negative,Negative,Yes
1,Moina,25,2nd,2nd,38 week,60 kg,5.2'',100/70,NaN,NaN,Normal,Normal,130m,NaN,Yes,Positive,Negative,No
2,Rabeya,20,1st,1st,30 week,55 kg,5.0'',100/60,NaN,NaN,Normal,Normal,120m,NaN,Yes,Negative,Negative,Yes
3,Shorna,22,1st,3rd,35 week,51 kg,5.4'',110/65,NaN,NaN,Normal,Normal,130m,NaN,Yes,Positive,Negative,Yes
4,Tania Akter,20,1st,2nd,30 week,53 kg,5.2'',100/55,NaN,NaN,Normal,Normal,125m,NaN,Yes,Negative,Negative,No

### Descriptive statistic
### Deskriptivna statistika

In [86]:
df.describe()

,dob,trudnoca_po_redu,tetanus_vakcina_po_redu,sedmica_trudnoce,tezina,visina,sistolicki_krvni_tlak,dijastolicki_krvni_tlak
count,998.000000,998.000000,998.000000,998.000000,998.000000,998.000000,998.000000,998.000000
mean,22.962926,1.166333,1.788577,28.938878,56.114228,159.989980,102.825651,64.574148
std,3.568168,0.385792,0.705609,4.969241,5.308816,5.308903,9.343101,7.914032
min,18.000000,1.000000,1.000000,20.000000,45.000000,152.000000,80.000000,55.000000
25%,20.000000,1.000000,1.000000,25.000000,52.000000,155.000000,100.000000,60.000000
50%,22.000000,1.000000,2.000000,30.000000,56.000000,158.000000,100.000000,60.000000
75%,25.000000,1.000000,2.000000,32.000000,61.000000,165.000000,110.000000,70.000000
max,32.000000,3.000000,3.000000,38.000000,65.000000,171.000000,120.000000,80.000000

### Displaying the missing values for each variable in dataset
### Prikaz nedostajućih vrijednosti za svaku varijablu u datasetu

In [53]:
print(df.isnull().sum())

ime                          0
dob                          0
trudnoca_po_redu             0
tetanus_vakcina_po_redu      0
sedmica_trudnoce             0
tezina                       0
visina                       0
krvni_pritisak               0
anemija                    875
zutica                     986
polozaj_fetusa               0
pokreti_fetusa               0
otkucaji_srca_fetusa         0
albumin_urin               864
test_urina_za_dijabetes      0
sifillis                     0
hepatitisb                   0
rizicna_trudnoca             0
dtype: int64

## Filling the missing values of categorocial variables with mode
## Popunjavanje nedostajućih vrijednosti za kategoričke varijable korištenjem mode vrijednosti

In [54]:
df['anemija'].unique()

array([nan, 'Minimal', 'Medium'], dtype=object)

In [56]:
print(df['anemija'].value_counts(dropna=False))

anemija
NaN        875
Minimal     62
Medium      61
Name: count, dtype: int64

In [57]:
df['zutica'].unique()

array([nan, 'Minimal', 'Medium'], dtype=object)

In [58]:
print(df['zutica'].value_counts(dropna=False))

zutica
NaN        986
Minimal      8
Medium       4
Name: count, dtype: int64

In [59]:
df['albumin_urin'].unique()

array([nan, 'Higher', 'Minimal', 'Medium'], dtype=object)

In [60]:
print(df['albumin_urin'].value_counts(dropna=False))

albumin_urin
NaN        864
Medium      48
Higher      44
Minimal     42
Name: count, dtype: int64

In [61]:
df['anemija'] = df['anemija'].fillna('None')
df['albumin_urin'] = df['albumin_urin'].fillna('Normal')

In [63]:
df['anemija'].unique()

array(['None', 'Minimal', 'Medium'], dtype=object)

#### Droping column "zutica" since we have a 98% of missing values in dataset
#### Brisanje kolone "zutica" obzirom da postoji preko 98% nedostajućih vrijednosti u dataset-u

In [64]:
df.drop(columns=['zutica'], inplace=True)

In [66]:
print(df.isnull().sum())

ime                        0
dob                        0
trudnoca_po_redu           0
tetanus_vakcina_po_redu    0
sedmica_trudnoce           0
tezina                     0
visina                     0
krvni_pritisak             0
anemija                    0
polozaj_fetusa             0
pokreti_fetusa             0
otkucaji_srca_fetusa       0
albumin_urin               0
test_urina_za_dijabetes    0
sifillis                   0
hepatitisb                 0
rizicna_trudnoca           0
dtype: int64

## Removing unnecessary column
## Uklanjanje kolone koja neće značiti tokom same analize

In [67]:
df.drop(columns = ['ime'], inplace=True)

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 998 entries, 0 to 997
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   dob                      998 non-null    int64
 1   trudnoca_po_redu         998 non-null    object
 2   tetanus_vakcina_po_redu  998 non-null    object
 3   sedmica_trudnoce         998 non-null    object
 4   tezina                   998 non-null    object
 5   visina                   998 non-null    object
 6   krvni_pritisak           998 non-null    object
 7   anemija                  998 non-null    object
 8   polozaj_fetusa           998 non-null    object
 9   pokreti_fetusa           998 non-null    object
 10  otkucaji_srca_fetusa     998 non-null    object
 11  albumin_urin             998 non-null    object
 12  test_urina_za_dijabetes  998 non-null    object
 13  sifillis                 998 non-null    object
 14  hepatitisb               998 non-null    object
 15  rizicna_trudnoca         998 non-null    object
dtypes: int64(1), object(15)
memory usage: 124.9+ KB

## Converting categorical variables into numerical
## Pretvaranje kategoričkih varijabli u numeričke

In [69]:
df['trudnoca_po_redu'].unique()

array(['1st', '2nd', '3rd'], dtype=object)

In [70]:
df['trudnoca_po_redu'] = df['trudnoca_po_redu'].map({'1st': 1, '2nd': 2, '3rd': 3})

In [71]:
print(df['trudnoca_po_redu'].dtype)

int64

In [72]:
df['tetanus_vakcina_po_redu'].unique()

array(['1st', '2nd', '3rd'], dtype=object)

In [73]:
df['tetanus_vakcina_po_redu'] = df['tetanus_vakcina_po_redu'].map({'1st': 1, '2nd': 2, '3rd': 3})

In [74]:
print(df['tetanus_vakcina_po_redu'].dtype)

int64

In [75]:
df['sedmica_trudnoce'].unique()

array(['38 week', '30 week', '35 week', '20 week', '23 week', '28 week',
       '25 week', '32 week', '26 week', '24 week', '36 week'],
      dtype=object)

In [76]:
df['sedmica_trudnoce'] = df['sedmica_trudnoce'].str.extract(r'(\d+)').astype(int)

In [77]:
print(df['sedmica_trudnoce'].dtype)

int64

In [78]:
df['tezina'].unique()

array(['50 kg', '60 kg', '55 kg', '51 kg', '53 kg', '61 kg', '52 kg',
       '62 kg', '58 kg', '56 kg', '65 kg', '49 kg', '45 kg', '63 kg'],
      dtype=object)

In [79]:
df['tezina'] = df['tezina'].astype(str).str.extract(r'(\d+)').astype(int)

In [80]:
print(df['tezina'].dtype)

int64

### Converting height from feets to cm
### Konverzija visine koja je izražena u feets u cm

In [81]:
df['visina'] = df['visina'].astype(str).str.replace("''", "", regex=False).astype(float)

df['visina'] = df['visina'] * 30.48

df['visina'] = df['visina'].round(0).astype(int)

In [82]:
print(df['visina'].dtype)

int64

### Seperating the value of blood preasure into two different columns: systolic and diastolic preassure
### Razdvajanje varijable krvni pritisak u dvije zasebne: donji krvni pritisak i gornji krvni pritisak

In [83]:
df[['sistolicki_krvni_tlak', 'dijastolicki_krvni_tlak']] = df['krvni_pritisak'].str.split('/', expand=True)

df['sistolicki_krvni_tlak'] = df['sistolicki_krvni_tlak'].astype(int)
df['dijastolicki_krvni_tlak'] = df['dijastolicki_krvni_tlak'].astype(int)

### Droping the original column for blood preasure since we now have a new variables
### Brisanje originalne kolone krvni pritisak obzirom da sada imamo dvije zasebne varijable

In [84]:
df.drop(columns=['krvni_pritisak'], inplace=True)

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 998 entries, 0 to 997
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   dob                      998 non-null    int64
 1   trudnoca_po_redu         998 non-null    int64
 2   tetanus_vakcina_po_redu  998 non-null    int64
 3   sedmica_trudnoce         998 non-null    int64
 4   tezina                   998 non-null    int64
 5   visina                   998 non-null    int64
 6   anemija                  998 non-null    object
 7   polozaj_fetusa           998 non-null    object
 8   pokreti_fetusa           998 non-null    object
 9   otkucaji_srca_fetusa     998 non-null    object
 10  albumin_urin             998 non-null    object
 11  test_urina_za_dijabetes  998 non-null    object
 12  sifillis                 998 non-null    object
 13  hepatitisb               998 non-null    object
 14  rizicna_trudnoca         998 non-null    object
 15  sistolicki_krvni_tlak    998 non-null    int64
 16  dijastolicki_krvni_tlak  998 non-null    int64
dtypes: int64(8), object(9)
memory usage: 132.7+ KB